version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ../Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
      - events_mssql:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
volumes:
  events_mssql: